eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pacientes
          uri: http://localhost:8091
          predicates:
            - Path=/api/pacientes/**
        - id: profesionales
          uri: http://localhost:8090
          predicates:
            - Path=/api/profesionales/**
        - id: turnos
          uri: http://localhost:8092
          predicates:
            - Path=/api/turnos/**